from app.models.base_model import BaseModel
import google.generativeai as genai
import json
import os
from abc import ABC, abstractmethod

class GeminiHateSpeechModel(BaseModel):
    '''
    A hate speech detection model powered by the Google Gemini API.
    '''
    def __init__(self, name: str, model_name: str = 'gemini-1.5-flash',
                 api_key : str = '') -> None:
        '''
        Initializes the Gemini model client.

        Args:
        - name (str)      : A user-friendly name for this model instance.
        - model_name (str): The specific Gemini model to use (e.g., 'gemini-1.5-flash').
        - api_key (str)   : Key to access the Gemini model

        Return:
        - None
        '''
        # Constructing the super class
        super().__init__(name)
        
        # Setting the api of genai
        genai.configure(api_key = api_key)
        
        # Constructing the model
        self.model = genai.GenerativeModel(model_name)

        # Storing the last input and response
        self._last_input    = None
        self._last_response = None

    def preprocess(self, text: str) -> str:
        '''
        Creates a structured prompt to get a JSON response from Gemini.
        
        Args:
            text (str): The raw text to analyze.
        
        Returns:
            str: A formatted prompt ready to be sent to the model.
        '''
        # Format of prompt to pass to model
        prompt = f"""
        You are a content moderation expert. Analyze the following text for hate speech.
        Respond ONLY with a valid JSON object. The JSON object must contain two keys:
        1. "hate_speech_probability": A float between 0.0 (not hate speech) and 1.0 (definitely hate speech).
        2. "explanation": A brief, one-sentence explanation for your reasoning.

        Text to analyze:
        ---
        {text}
        ---
        """
        # Ensure leading and trailing white spaces are removed
        return prompt.strip()

    def _get_prediction_from_api(self, preprocessed_input: str) -> dict:
        '''
        Internal method to call the API and parse the JSON, with caching.
        
        Input args:
        - preprocessed_input (str) : String that has already been through preprocess

        Return:
        - (dict)
        '''
        # Use cached response if the input is identical to the last one
        if self._last_input == preprocessed_input and self._last_response:
            return self._last_response

        # Call the API
        response = self.model.generate_content(preprocessed_input)
        
        # Cache the input and attempt to parse the response
        self._last_input = preprocessed_input
        try:

            # Clean up the response to ensure it's valid JSON
            clean_response = response.text.strip().replace('```json', '').replace('```', '')
            self._last_response = json.loads(clean_response)
        
        # Catching errors
        except (json.JSONDecodeError, AttributeError):

            # If parsing fails, return a default "error" state
            self._last_response = {
                'hate_speech_probability': 0.0,
                'explanation'            : 'Error: Could not parse model output.'
            }
        
        # Else, parsing a valid output
        return self._last_response

    def predict(self, preprocessed_input: str) -> float:
        '''
        Predicts the probability of the text being hate speech.

        Args:
            preprocessed_input (str): The prompt generated by the preprocess method.

        Returns:
            float: The probability score (0.0 to 1.0).
        '''
        # Calling the internal method to call API
        response_dict = self._get_prediction_from_api(preprocessed_input)

        # Returning a probability
        # If it doesn't exist, putting a 0
        return response_dict.get('hate_speech_probability', 0.0)

    def predict_text(self, preprocessed_input: str) -> str:
        '''
        Gets the model's textual explanation for its prediction.

        Args:
            preprocessed_input (str): The prompt generated by the preprocess method.

        Returns:
            str: The textual explanation.
        '''
        # Ensuring text is available
        response_dict = self._get_prediction_from_api(preprocessed_input)

        # Retrieving the explanation
        # - Defaults to no expalantion if it doesn't work
        return response_dict.get('explanation', 'No explanation available.')

    def load(self, model_path: str) -> None:
        '''
        No-op: The model is cloud-based and does not need to be loaded from a file.
        '''
        # If method is called, putting announcement to this effect
        print(f"'{self.name}' is a cloud-based API model; no loading from '{model_path}' is required.")

        # Passing without actualyl doing anything
        pass

    def save(self, model_path: str):
        '''
        No-op: The model is cloud-based and cannot be saved to a file.
        '''
        # Notifying that save is not needed
        print(f"'{self.name}' is a cloud-based API model and cannot be saved to '{model_path}'.")

        # Passing without doing anything
        pass